services:
  snapcast:
    image: docker.io/sweisgerber/snapcast:latest
    container_name: snapserver
    hostname: snapcast
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=${TZ:-Asia/Shanghai}
      - START_SNAPCLIENT=false
      - HOME=/data
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
    volumes:
      - ./snapcast/config:/config
      - ./snapcast/data:/data
      - ./data/audio:/audio
      - /etc/localtime:/etc/localtime:ro

  mopidy:
    image: docker.io/sweisgerber/mopidy:latest
    container_name: mopidy
    hostname: mopidy
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1001
      - TZ=${TZ:-Asia/Shanghai}
    ports:
      - "6600:6600"
      - "6680:6680"
    volumes:
      - ./mopidy/config:/config
      - ./data:/data
      - ${MUSIC_DIR:-./music}:/music:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - snapcast
