[core]
cache_dir = /data/cache
data_dir = /data

[logging]
config_file =

[audio]
mixer = software
mixer_volume =
output = audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=2,format=S16LE ! filesink location=/data/audio/snapcast_fifo

[mpd]
enabled = true
hostname = 0.0.0.0
port = 6600
max_connections = 20
connection_timeout = 60

[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[m3u]
enabled = true
playlists_dir = /data/playlists

[softwaremixer]
enabled = true

[file]
enabled = true
media_dirs =
  /music|Music
excluded_file_extensions =
  .jpg
  .jpeg
  .png
  .gif
  .db
  .m3u
  .m3u8
  .pls
  .cue
  .nfo

[local]
enabled = true
media_dir = /music
scan_timeout = 1000
scan_flush_threshold = 100
excluded_file_extensions =
  .m3u
  .m3u8
  .pls
  .cue
  .jpg
  .jpeg
  .png
  .gif
  .db
  .nfo
