[stream]
stream = pipe:///audio/snapcast_fifo?name=Mopidy&sampleformat=44100:16:2&codec=pcm

[http]
bind_to_address = 0.0.0.0
port = 1780
doc_root = /usr/share/snapweb

[tcp-control]
bind_to_address = 0.0.0.0
port = 1705

[server]
send_to_muted = false

[logging]
filter = *:info

[buffer]
ms = 1000
